##
## Copyright (c) 2024 TUM Department of Electrical and Computer Engineering.
##
## This file is part of Seal5.
## See https://github.com/tum-ei-eda/seal5.git for further info.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

name: Trigger ETISS Test Flow and wait for completion

on:
  pull_request:
    branches: [ "coredsl2" ]
    paths:
      - m2isar/frontends/coredsl2/**
      - m2isar/metamodel/**
      - m2isar/backends/etiss/**
      - .github/workflows/**

jobs:
  trigger_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Seal5 ETISS Test Flow
      uses: peter-evans/repository-dispatch@v3
      with:
         token: ${{ secrets.SEAL5_ACCESS_TOKEN }}
         repository: tum-ei-eda/seal5_etiss_test_env
         event-type: m2isar-event
         client-payload: '{"triggered_run_id": "${{ github.run_id }}", "ref": "${{ github.event.pull_request.head.sha }}", "from": "m2isar", "is_pr": "true"}'
    - name: Wait for Workflow Completion
      run: |
        echo "const https = require('https');
        const MAX_ATTEMPTS = 8;
        let attempt = 0;
        const current_time = new Date();
        console.log('Current Time: ', current_time.toISOString());
        const tenSecsEarlier = new Date(current_time.getTime() - 10000);
        const thirtySecsLater = new Date(current_time.getTime() + 30000);
        async function checkWorkflowStatus() {
          const options = {
            hostname: 'api.github.com',
            path: '/repos/tum-ei-eda/seal5_etiss_test_env/actions/runs',
            method: 'GET',
            headers: {
              'Authorization': 'Bearer ${{ secrets.SEAL5_ACCESS_TOKEN }}',
              'Accept': 'application/vnd.github.v3+json',
              'User-Agent': 'Node.js Script'
            }
          };
          // console.log('Options:', options);
          return new Promise((resolve, reject) => {
            https.get(options, (res) => {
              let data = '';
              res.on('data', (chunk) => {
                data += chunk;
              });
              res.on('end', () => {
                const response = JSON.parse(data);
                if (!response.workflow_runs) {
                  console.error('Unexpected response structure:', response);
                  reject('Invalid API response');
                  return;
                }
                // console.log('Responses:', response.workflow_runs);
                // console.log('Response:', response.workflow_runs[0].status);
                const workflowRuns = response.workflow_runs.filter(run =>
                  new Date(run.created_at) > new Date(tenSecsEarlier) &&
                  new Date(run.created_at) < new Date(thirtySecsLater) &&
                  run.event === 'repository_dispatch' &&
                  run.display_title === 'm2isar-event' &&
                  run.path === '.github/workflows/default.yml'
                );
                // console.log('workflowRuns:', workflowRuns);
                if (workflowRuns.length > 0) {
                  const status = workflowRuns[0].status;
                  const url = workflowRuns[0].html_url;
                  const conclusion = workflowRuns[0].conclusion;
                  console.log('URL of the matching workflow run: ', url);
                  console.log('Status of the matching workflow run: ', status);
                  // Check if the workflow run is completed
                  if (status === 'completed') {
                      console.log('Completed matching workflow run: ', status, conclusion);
                      resolve({ status, conclusion });  // Resolving both status and conclusion
                  } else {
                      console.log('Workflow run is not completed yet');
                      resolve({ status, conclusion: null }); // Conclusion is null if not completed
                  }
              } else {
                  console.log('No workflow runs found');
                  reject('No workflow runs found');  // Reject if no workflow runs are found
              }
              });
            }).on('error', (e) => {
              console.error(e);
              reject(e);
            });
          });
        }
        async function waitForWorkflowCompletion() {
          let res = {};
          while (attempt < MAX_ATTEMPTS) {
             try {
                res = await checkWorkflowStatus();
              } catch (error) {
                console.error('Error checking workflow status:', error);
              }
              // ... handle status and conclusion ...
            if (res && res.status === 'completed' && res.conclusion === 'success') {
              console.log('Workflow completed and test passed!');
              break
            } else if (res && res.status === 'completed' && res.conclusion === 'failure') {
              console.log('Workflow status is failed...');
              process.exit(1);
            } else if (res?.status !== '') {
              console.log('Workflow status is ' + res?.status + '. Waiting for completion...');
            } else {
              console.log('Workflow status is unknown. Waiting for completion...');
            }
            attempt++;
            console.log('Attempt: ' + attempt);
            await new Promise(resolve => setTimeout(resolve, 60000)); // 60 seconds
          }
          if (attempt === MAX_ATTEMPTS) {
            console.log('Max attempts reached without completion. Exiting.');
            process.exit(1);
          }
        }
        waitForWorkflowCompletion();" > script.js
        node script.js
    env:
      GITHUB_TOKEN: ${{ secrets.SEAL5_ACCESS_TOKEN }}`
